---
name: Update Lambda Template

inputs:
  aws-account-id:
    description: 'AWS Account ID'
    required: true
  aws-role-name:
    description: 'AWS Role Name'
    required: true
  aws-lambda-name:
    description: 'AWS Lambda Name'
    required: true
  aws-s3-bucket-name:
    description: 'AWS S3 Bucket Name'
    required: true

permissions:
  contents: read

runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/checkout@v3
  - name: Compress code files
    shell: bash
    env:
      AWS_ACCOUNT_ID: ${{ inputs.aws-account-id }}
    run: |
      zip lambda_function.zip lambda_function.py
      echo $AWS_ACCOUNT_ID
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-region: us-west-2
      role-to-assume: arn:aws:iam::166845317680:role/actions_s3_lambda
      role-session-name: myGitHubActions
  - name: Copy files to S3 bucket
    shell: bash
    env:
      AWS_S3_BUCKET_NAME: ${{ inputs.aws-s3-bucket-name }}
    run: |
      aws s3 cp lambda_function.zip s3://$AWS_S3_BUCKET_NAME
  - name: Update Lambda function
    shell: bash
    env:
      AWS_LAMBDA_NAME: ${{ inputs.aws-lambda-name }}
      AWS_S3_BUCKET_NAME: ${{ inputs.aws-s3-bucket-name }}
    run : |
      aws lambda update-function-code --function-name $AWS_LAMBDA_NAME --s3-bucket $AWS_S3_BUCKET_NAME --s3-key "lambda_function.zip" --region us-west-2