---
name: Update Lambda

on:
  push:
    branches:
      - main
      - release

permissions:
  id-token: write
  contents: read

jobs:
  update-lambda:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/release' && 'prod' || 'test' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Update Lambda Template
        uses: ./.github/actions/update-lambda
        with:
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          aws-role-name: ${{ secrets.AWS_ROLE_NAME }}
          aws-lambda-name: ${{ secrets.AWS_LAMBDA_NAME }}
          aws-s3-bucket-name: ${{ secrets.AWS_S3_BUCKET_NAME }}
