---
name: Update Lambda

on:
  push:
    branches:
      - main
      - release

jobs:
  update-lambda-test:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Update Lambda Template
        uses: Beshlawy-s/actions-lambda-poc/.github/workflows/template.yml@main

  update-lambda-prod:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Update Lambda Template
        uses: Beshlawy-s/actions-lambda-poc/.github/workflows/template.yml@release
