---
name: Update Lambda

jobs:
  update-lambda-test:
    if: github.ref == 'refs/heads/main'
    name: update-lambda-test
    environment: test
    uses: Beshlawy-s/actions-lambda-poc/.github/workflows/template.yml@main

  update-lambda-prod:
    if: github.ref == 'refs/heads/release'
    environment: prod
    name: update-lambda-prod
    uses: Beshlawy-s/actions-lambda-poc/.github/workflows/template.yml@release
      